/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Lenovo
 */
public class VAdministratorDashboard extends javax.swing.JFrame {

    /**
     * Creates new form AdministratorDashboard
     */
    public VAdministratorDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnVstaffRegistrationAndDetails = new javax.swing.JButton();
        btnVViewStaffAttendance = new javax.swing.JButton();
        btnVViewAssignedTasks = new javax.swing.JButton();
        labelVStaffRegistrationAndDetails = new javax.swing.JLabel();
        labelVViewStaffAttendance = new javax.swing.JLabel();
        labelVViewAssignedTasks = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administrator Dashboard - Staff Management System");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        btnVstaffRegistrationAndDetails.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnVstaffRegistrationAndDetails.setText("View Staff Information");
        btnVstaffRegistrationAndDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVstaffRegistrationAndDetailsActionPerformed(evt);
            }
        });

        btnVViewStaffAttendance.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnVViewStaffAttendance.setText("View Staff Attendance");
        btnVViewStaffAttendance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVViewStaffAttendanceActionPerformed(evt);
            }
        });

        btnVViewAssignedTasks.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnVViewAssignedTasks.setText("View Staff Assinged Tasks ");
        btnVViewAssignedTasks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVViewAssignedTasksActionPerformed(evt);
            }
        });

        labelVStaffRegistrationAndDetails.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Documents\\Staff Managment System (with MVC)\\images\\staff.jpg")); // NOI18N
        labelVStaffRegistrationAndDetails.setText("jLabel1");
        labelVStaffRegistrationAndDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelVStaffRegistrationAndDetailsMouseClicked(evt);
            }
        });

        labelVViewStaffAttendance.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Documents\\Staff Managment System (with MVC)\\images\\attendance.jpg")); // NOI18N
        labelVViewStaffAttendance.setText("jLabel2");
        labelVViewStaffAttendance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelVViewStaffAttendanceMouseClicked(evt);
            }
        });

        labelVViewAssignedTasks.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Documents\\Staff Managment System (with MVC)\\images\\tasks.jpg")); // NOI18N
        labelVViewAssignedTasks.setText("jLabel3");
        labelVViewAssignedTasks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelVViewAssignedTasksMouseClicked(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Select An Option to Continue:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelVStaffRegistrationAndDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVstaffRegistrationAndDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelVViewStaffAttendance, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVViewStaffAttendance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelVViewAssignedTasks, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVViewAssignedTasks, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(102, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(291, 291, 291))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelVStaffRegistrationAndDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelVViewStaffAttendance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelVViewAssignedTasks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVstaffRegistrationAndDetails)
                    .addComponent(btnVViewStaffAttendance)
                    .addComponent(btnVViewAssignedTasks))
                .addGap(79, 79, 79))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 89, -1, -1));

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Staff Management System");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Documents\\Staff Managment System (with MVC)\\images\\background.jpg")); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 0, 1010, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVstaffRegistrationAndDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVstaffRegistrationAndDetailsActionPerformed
        VStaffRegistrationAndDetails staff_registration = new VStaffRegistrationAndDetails();
        staff_registration.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVstaffRegistrationAndDetailsActionPerformed

    private void btnVViewStaffAttendanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVViewStaffAttendanceActionPerformed
        VViewStaffAttendance staff_attendance = new VViewStaffAttendance();
        staff_attendance.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVViewStaffAttendanceActionPerformed

    private void btnVViewAssignedTasksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVViewAssignedTasksActionPerformed
        VViewAssignedTasks assigned_tasks = new VViewAssignedTasks();
        assigned_tasks.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVViewAssignedTasksActionPerformed

    private void labelVStaffRegistrationAndDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelVStaffRegistrationAndDetailsMouseClicked
        VStaffRegistrationAndDetails staff_registration = new VStaffRegistrationAndDetails();
        staff_registration.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_labelVStaffRegistrationAndDetailsMouseClicked

    private void labelVViewStaffAttendanceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelVViewStaffAttendanceMouseClicked
        VViewStaffAttendance staff_attendance = new VViewStaffAttendance();
        staff_attendance.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_labelVViewStaffAttendanceMouseClicked

    private void labelVViewAssignedTasksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelVViewAssignedTasksMouseClicked
        VViewAssignedTasks assigned_tasks = new VViewAssignedTasks();
        assigned_tasks.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_labelVViewAssignedTasksMouseClicked

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        VStaffLogin staff_login = new VStaffLogin();
        staff_login.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VAdministratorDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VAdministratorDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VAdministratorDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VAdministratorDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VAdministratorDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnVViewAssignedTasks;
    private javax.swing.JButton btnVViewStaffAttendance;
    private javax.swing.JButton btnVstaffRegistrationAndDetails;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelVStaffRegistrationAndDetails;
    private javax.swing.JLabel labelVViewAssignedTasks;
    private javax.swing.JLabel labelVViewStaffAttendance;
    // End of variables declaration//GEN-END:variables
}
